import {
  mdiCheckCircle,
  mdiAlertCircle,
  mdiAlert,
  mdiInformation,
  mdiClose,
  mdiChevronDown,
  mdiChevronUp,
  mdiImport,
  mdiMenu,
  mdiTrashCan,
  mdiDownload,
  mdiDownloadCircleOutline,
  mdiFileUpload,
  mdiFileCodeOutline,
  mdiCheckCircleOutline,
  mdiContentSave,
  mdiArrowDown,
  mdiViewDashboard,
  mdiFolder,
  mdiOpenInNew,
  mdiFileDocumentOutline,
  mdiFilePdfBox,
  mdiFileImageOutline,
  mdiFile,
  mdiKeyboard,
  mdiUnfoldMoreHorizontal,
  mdiFilter,
  mdiFilterOutline,
  mdiFileEye,
} from '@mdi/js';

export const iconMap = {
  mdiCheckCircle,
  mdiAlertCircle,
  mdiAlert,
  mdiInformation,
  mdiClose,
  mdiChevronDown,
  mdiChevronUp,
  mdiImport,
  mdiMenu,
  mdiTrashCan,
  mdiDownload,
  mdiDownloadCircleOutline,
  mdiFileUpload,
  mdiFileCodeOutline,
  mdiCheckCircleOutline,
  mdiContentSave,
  mdiArrowDown,
  mdiViewDashboard,
  mdiFolder,
  mdiOpenInNew,
  mdiFileDocumentOutline,
  mdiFilePdfBox,
  mdiFileImageOutline,
  mdiFile,
  mdiKeyboard,
  mdiUnfoldMoreHorizontal,
  mdiFilter,
  mdiFilterOutline,
  mdiFileEye,
} as const;

export type IconName = keyof typeof iconMap;
